### ISSUE TITLE
SalmonTE on Galaxy server

### ISSUE THREAD

**Issue by sarah872** [hyunhwaj/SalmonTE#1] opened 2017-12-12 10:15 UTC
Does anyone know if it is already available through a publicGalaxy server?

**Comment by hyunhwaj** [comment] 2017-12-12 17:44
Hi @sarah872,

Thank you for your interested `SalmonTE`. I have not had any experience making any pipeline of mine available through a publicGalaxy server, but I believe it must be great to put this tool on the server. I will make a future plan on it, but I have to ask your patients to do it. I will be glad to any further suggestion or be providing any useful materials to help the implementation. 

If you want to run `SalmonTE` right now and have any problem, then please do not hesitate to ask any question. I will glad to assist you.

Best,

Hyun-Hwan Jeong

**Comment by sarah872** [comment] 2017-12-12 18:32
I am asking because (1) you reported problems when running on MacOS and (2) I could run it in a cluster, but for that the admin needs to install it

keep me updated! thanks

**Comment by hyunhwaj** [comment] 2017-12-12 20:00
I will start work to solve the issue of MacOS with `docker` and will give an update in this week even it has not been finished.

For the `pip3` issue, I believe `pip3` must find the package, would you try below command? 

`pip3 install git+git://github.com/docopt/docopt --user`

Best,

Hwan

**Comment by sarah872** [comment] 2017-12-12 20:02
getting the following when trying your command:
`Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.2 from git+https://github.com/docopt/docopt in /Users/Tobias/Library/Python/3.6/lib/python/site-packages`

**Comment by hyunhwaj** [comment] 2017-12-12 21:08
@sarah872,

The message shows the package has been installed. Are you having any problem and seeing any error message when you run `salmonTE`?

Thank you,

Hyun-Hwan Jeong

**Comment by hyunhwaj** [comment] 2017-12-12 21:24
Hi @sarah872,

I also have another thought for how to run it in your computing environment:

1. As we know, running it on`macOS` may have a problem and I am still figuring out, so it will take the time to solve the issue. Are you trying to install it on your `macOS` machine now? I guess multiple obstacles will wait for you to run, so I would not recommend you to take this option now.

2. However, if you have a Linux machine and `python3` is installed (I guess the OS is installed the cluster, so you are in the case), then `SalmonTE` can be installed with your account (i.e. without `root` or `admin` account), and you can use this pipeline in the machine.

Thank you,

Hyun-Hwan Jeong

**Comment by sarah872** [comment] 2017-12-13 11:28
I will wait then as I don't have permissions to install packages 
keep me posted!

**Comment by hyunhwaj** [comment] 2017-12-14 07:12
Dear @sarah872,

I figured out the `macOS` problem was because `snakemake` which I used in one of my  machine was outdated. The problem is resolved with upgrading the `snakemake` package, and you can try it. Please let me know if you have any problem, and I will open another issue for the `macOS` to explore your issue.

For the version public galaxy server, it would be difficult to implement it, so I am seeing another way to ease installation of the tool. I believe using [`docker`](https://docs.docker.com/) must be the answer, and I will start the implementation soon. Please note me you are fine with the option, and I will close this issue once I got the answer from you.

Best Regards,

Hyun-Hwan Jeong

**Comment by sarah872** [comment] 2017-12-14 08:26
Dear @hyunhwaj 
I am still getting the error:
```
dos13:SalmonTE Sarah$ python3 SalmonTE.py 

Traceback (most recent call last):
  File "SalmonTE.py", line 14, in <module>
    from docopt import docopt
ImportError: No module named 'docopt'
```

**Comment by hyunhwaj** [comment] 2017-12-14 09:47
@sarah872 Could you write down the problem #2 after now? 

By the way, I guess you have multiple version of `python3` now. Could you provide output of `pip3 --version` and `python3 --version` for the clarification fo the problem? Moreover, I would you ask to run following commands.

```
git clone https://github.com/docopt/docopt
cd docopt
python3 setup.py install
```

Thank you,

Hyun-Hwan Jeong

**Closed** 2017-12-14 10:27 UTC
Labels: enhancement
